# Generated by Django 4.2.1 on 2023-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_pattern_test_test_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='answers',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blank',
            name='image',
            field=models.ImageField(upload_to='blanks/', verbose_name='Фотография бланка'),
        ),
    ]
